# Generated by Django 3.2 on 2021-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_usr_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='usr',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
    ]
