# Generated by Django 3.2 on 2021-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210509_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='username',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
