# Generated by Django 3.2 on 2021-05-11 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0004_usr_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr',
            name='username',
        ),
        migrations.AddField(
            model_name='usr',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
