# Generated by Django 3.2 on 2021-05-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_usr_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usr',
        ),
    ]
